services:
  - type: web
    name: irhis-backend
    env: python
    region: frankfurt
    plan: free
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w $WEB_CONCURRENCY -k uvicorn.workers.UvicornWorker main:app"
    healthCheckPath: "/"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DB_USER
        fromDatabase:
          name: irhis-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: irhis-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: irhis-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: irhis-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: irhis-db
          property: database
databases:
  - name: irhis-db
    region: frankfurt
    plan: free
    postgresMajorVersion: 15 