services:
  - type: web
    name: irhis-backend
    env: python
    region: frankfurt
    plan: free
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w $WEB_CONCURRENCY -k uvicorn.workers.UvicornWorker main:app"
    healthCheckPath: "/"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: irhis-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: irhis-db
    databaseName: irhis
    plan: free 