name: Deploy Python app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v4

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'irhis-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend' 